### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by jordaaash** [GooseFX1/gfx-web-app#531]
Input:
```shell
git clone https://github.com/GooseFX1/gfx-web-app.git
cd gfx-web-app
yarn --pure-lockfile
yarn start
```

Output:
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/jordan/gfx-web-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/jordan/gfx-web-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/jordan/gfx-web-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/jordan/gfx-web-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/jordan/gfx-web-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/jordan/gfx-web-app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by stunt101harm** [comment]
i believe you need to use `nvm use v16` before building then run `npm install`

**Comment by jordaaash** [comment]
Ah, thanks. Doing that now. Any idea what's breaking it between Node 16 and 18?

**Comment by walt-1** [comment]
The nvmrc file is currently set to use `14.18.0`. Running `nvm use` will set it for the local dev environment. Planning to update in the future.

**Comment by jordaaash** [comment]
This fixed it! I used https://github.com/tj/n to install 16.18.0.
